[package]
name = "borrow_me_the_reference"
version = "0.1.0"
<<<<<<< HEAD
edition = "2024"
=======
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
>>>>>>> 7429200b1f3aa984f7ea963145f6c57ebdfc133d

[dependencies]
